# Generated by Django 5.2.4 on 2025-07-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_original_price_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=False),
        ),
    ]
